services:
  rstudio:
    image: cecadbif/rstudio-crc-image:4.1.2
    container_name: rstudio-crc
    ports:
      - "54499:8787"
    volumes:
      - type: "bind"
        source: "$HOME/.gitconfig"
        target: "/home/rstudio/.gitconfig"
      - type: "bind"
        source: "/mnt/raid1/projects/2_primary.analysis/AG_Kashkar/Role-of-XIAP-in-Colorectal-Cancer"
        target: "/home/rstudio/project"
    environment:
      - USERNAME=ugoebel
      - USERID=1000
      - GROUPID=1000
      - USER=rstudio
      - PASSWORD=1rstudio
